workflows:
  android-release:
    name: Android Release APK Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Initialize Flutter Project
        script: | 
          flutter create . --platforms android --project-name zx_calculator
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build Android APK
        script: | 
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - zsdev07@gmail.com
        notify:
          success: true
          failure: true
